### ISSUE TITLE
Return in addition property chain of result(s)

### ISSUE THREAD

**Issue by Miklet** [rowanoulton/prefix-matches#1]
In reference to https://github.com/kentcdodds/nps/issues/126 it would be nice if result would also contains it's property chain e.x.:
```
foo: {
  bar: 'echo f.b',
  baz: 'echo f.b'
}
```
and for prefix `f.b` the result should be following: 
```
[{ 'foo.bar': 'echo f.b' }, { 'foo.baz': 'echo f.b' }]
```

**Comment by kentcdodds** [comment]
I'm in favor! Would love to see a pull request for this!

**Comment by Miklet** [comment]
I've managed to do this by reimplementing current solution a little bit. Mainly from iterative way to recursive which was easier to gain expected result. Before I make a PR with WIP I wanted to ask what is minimal node version we target. I saw that latest commit was for supporting Node 0.10. Is it still actual? This project is only used by nps, shouldn't we target same version?

**Comment by kentcdodds** [comment]
I think that Node v4 is the lowest I care to support.

**Comment by Miklet** [comment]
Uhhh I made one typo in README:
```
// Resolves simple cases
prefixMatches('w', {
	watch: 'watch things',
	build: 'build things'
}) // => [{ watch: 'watch things']
```
A closing bracket (**}**) is missing. @kentcdodds or @rowanoulton could you fix it in direct commit, I think there is no point to reopen PR or make another one for such thing. Sorry for that.

**Comment by kentcdodds** [comment]
Fixed.
